FROM node:latest 

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    imagemagick libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
    && docker-php-ext-enable imagick

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "node", "main.js" ]
