FROM node:latest 

WORKDIR /usr/src/app

ENV DEBIAN_FRONTEND=noninteractive

RUN wget https://download.imagemagick.org/ImageMagick/download/releases/ImageMagick-7.1.1-15.tar.xz && \
    tar -xf ImageMagick-7.1.1-15.tar.xz && \
    cd ImageMagick-7.1.1-15 && \
    ./configure && \
    make && \
    make install && \
    ldconfig

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "node", "main.js" ]
