FROM node:latest 

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y imagemagick libmagickcore-6.q16-6 libmagickwand-6.q16-6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "node", "main.js" ]
